spring:
  application:
    name: eduspace-backend
  datasource:
    url: jdbc:mysql://localhost:3306/eduspace?createDatabaseIfNotExist=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
